name: Rebase

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        branch: [lineage-19.1, lineage-20.0, lineage-21.0]
        repo: [android, android_build_make, android_frameworks_base, android_frameworks_native, android_packages_apps_Settings, android_packages_apps_Trebuchet, android_system_core, android_vendor_lineage]
    name: Automatic rebase
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"

        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/droid-legacy/${{ matrix.repo }} -b ${{ matrix.branch }}
        cd ${{ matrix.repo }}
        git fetch https://github.com/LineageOS/${{ matrix.repo }}.git ${{ matrix.branch }}
        git rebase FETCH_HEAD
        git push -f

      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
